#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

docker run $CI_ENV \
           -e ENABLE_CODECOV=1 -e CI=true \
           -v $DIR/..:/code \
           -w /code \
           openstax/kitchen-ci:latest \
           rspec
