FROM ruby:2.6

ARG bundler_version

WORKDIR /code
COPY . /code/

RUN gem install bundler --no-document --version $bundler_version && \
    bundle config set no-cache 'true' && \
    bundle config set silence_root_warning 'true' && \
    bundle install
