FROM ruby:2.6

ARG bundler_version

RUN gem install bundler --no-document --version $bundler_version

WORKDIR /code
COPY . /code/


    # # bundle config set no-cache 'true' && \
    # bundle config path vendor/bundle
    # bundle install
