# frozen_string_literal: true

require 'spec_helper'

RSpec.describe Kitchen::NoteElement do
  let(:short_name) { :book1 }

  let(:book_with_notes) do
    book_containing(short_name: short_name, html:
      one_chapter_with_one_page_containing(
        <<~HTML
          <div data-type="note" id="noteId" class="chemistry link-to-learning">
            <p id="pId">Blah</p>
          </div>
          <div data-type="note" id="noteId" class="bad-class">
            <p id="pId">Blah</p>
          </div>
        HTML
      ))
  end

  let(:untitled_note) { book_with_notes.notes.first }

  let(:unclassified_note) { book_with_notes.notes[1] }

  describe '#autogenerated_title' do
    before do
      stub_locales({
        'book1': {
          'notes': {
            'link-to-learning': 'Chemistry',
            'everyday-life': 'Chemistry in Everyday Life'
          }
        },
        'book2': {}
      })
    end

    context 'when book has a title in locales' do
      it 'gives the book specific title' do
        expect(untitled_note.autogenerated_title).to eq 'Chemistry'
      end
    end

    context 'when book does not have a title in locales' do
      let(:short_name) { :foo }

      it 'tells you' do
        expect($stdout).to receive(:puts).with("Entry for book with short name #{untitled_note.document.short_name} does not exist in locales")
        untitled_note.autogenerated_title
      end

      it 'returns filler' do
        allow($stdout).to receive(:puts) # suppress output
        expect(untitled_note.autogenerated_title).to eq '[unknown note title]'
      end
    end

    context 'when the key "notes" does not exist under book title' do
      let(:short_name) { :book2 }

      it 'tells you' do
        expect($stdout).to receive(:puts).with("The book #{unclassified_note.document.short_name} does not have an entry for notes in locales")
        unclassified_note.autogenerated_title
      end
    end

    context 'when title for the given class does not exist' do
      it 'tells you' do
        expect($stdout).to receive(:puts).with('Title for note with classes ["bad-class"] not found')
        unclassified_note.autogenerated_title
      end
    end
  end

  it 'can get its own enumerator' do
    expect(untitled_note.as_enumerator).to be_a Kitchen::NoteElementEnumerator
  end

end
