name: Tests

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  tests:
    timeout-minutes: 10
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build docker image and run specs within it
        # env:
        #   ENABLE_CODECOV: 1
        run: |
          ./docker/build --ci

          CI_ENV=`bash <(curl -s https://codecov.io/env)`
          echo "ENV VARS 1"
          echo $CODECOV_ENV
          echo $CODECOV_TOKEN
          echo $CODECOV_URL
          echo $CODECOV_SLUG
          echo $VCS_COMMIT_ID
          echo $VCS_BRANCH_NAME
          echo $VCS_PULL_REQUEST
          echo $VCS_SLUG
          echo $VCS_TAG
          echo $CI_BUILD_URL
          echo $CI_BUILD_ID
          echo $CI_JOB_ID
          echo $GITHUB_ACTIONS
          echo $GITHUB_REF
          echo $GITHUB_REPOSITORY
          echo $GITHUB_HEAD_REF
          echo $GITHUB_SHA
          echo $GITHUB_RUN_ID

          CI_ENV=`bash <(curl -s https://codecov.io/env)` ./docker/ci

  # tests:
  #   timeout-minutes: 10
  #   runs-on: ubuntu-18.04

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-ruby@v1
  #       with:
  #         ruby-version: 2.6.6
  #     - uses: actions/cache@v2
  #       with:
  #         path: vendor/bundle
  #         key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
  #         restore-keys: |
  #           ${{ runner.os }}-gems-
  #     - name: Test
  #       env:
  #         ENABLE_CODECOV: 1
  #       run: |
  #         gem install bundler --force --no-document --version 2.2.4
  #         bundle config deployment true
  #         bundle config path vendor/bundle
  #         bundle config jobs 2
  #         bundle install
  #         bundle exec rake
